# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Netlfix' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'Auk', '~> 7.0'

  # Pods for Netlfix

  target 'NetlfixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetlfixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
